name: Build Docker Image and Deploy to App Engine
run-name: ${{ github.actor }} is building Docker Image
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into the github container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push the docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
